- name: install rsync
  yum: name=rsync

- name: create /var/lock/dss
  file: state=directory dest=/var/lock/dss owner=wso2_dss

- name: put /home/wso2_dss/rsync-for-carbon-depsync.sh
  template: src=rsync-for-carbon-depsync.sh dest=/home/wso2_dss/rsync-for-carbon-depsync.sh mode=0755

- name: put workers-list.txt
  template: src=workers-list.txt dest=/home/wso2_dss/workers-list.txt

- name: add a cron job
  template: src=wso2_dss dest=/etc/cron.d/wso2_dss
